### ISSUE TITLE
only first rule works in nirvana.yaml

### ISSUE THREAD

**Issue by moshuipan** [caicloud/nirvana#337]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
edit nirvana.yaml 
```yaml
......
versions:
- name: v1
  rules:
  - prefix: /apis/v1
  - prefix: /healthz
......
```
only first rule `/apis/v1` works
**What you expected to happen**:
api.json  contains healthz
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
[generator.go](https://github.com/caicloud/nirvana/blob/master/utils/generators/swagger/generator.go#L171-L177)
`path = rule.Replace(path)`
the path will be set to empty if rule do not match .
